#!/usr/bin/env bash

DOTFILES="$HOME/dotfiles"
if [ -e "$DOTFILES/vimrc" ]; then
  echo "Already installed"
  exit 0
fi

echo "Symlinking:"
ln -s ~/dotfiles/zshrc ~/.zshrc
echo "  * zshrc"
ln -s ~/dotfiles/zshrc ~/.zshenv
echo "  * zsenv"
ln -s ~/dotfiles/zlogin ~/.zlogin
echo "  * zlogin"
ln -s ~/dotfiles/vimrc ~/.vimrc
echo "  * vimrc"
ln -s ~/dotfiles/bashrc ~/.bashrc
echo "  * bashrc"
ln -s ~/dotfiles/vim ~/.vim
echo "  * irbrc"
ln -s ~/dotfiles/irbrc ~/.irbrc
echo "  * vim/"
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
echo "  * tmux.conf"
ln -s ~/dotfiles/gitconfig ~/.gitconfig
echo "  * gitconfig"
ln -s ~/dotfiles/cvsignore ~/.cvsignore
echo "  * gitignore (actually cvsignore)"

echo "Use ctrl-w and ctrl-u everywhere on macOS"
mkdir "$HOME/Library/KeyBindings"
cp "$DOTFILES/macos_DefaultKeyBinding.dict" "$HOME/Library/KeyBindings/DefaultKeyBinding.dict"

echo "NVIM c-h thinger"
infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
tic $TERM.ti
