#!/usr/bin/env bash

WORK_DIR="$HOME/dotfiles"

DOTFILES="alacritty.yml \
  zshrc \
  zshenv \
  zlogin \
  bashrc \
  tmux.conf \
  vim \
  vimrc \
  init.vim \
  gitconfig \
  cvsignore \
  psqlrc \
  irbrc \
  gemrc"

echo "Symlinking:"

for file in $DOTFILES; do
  ln -s "$WORK_DIR/$file" "$WORK_DIR/.$file"
  echo "  * $file"
done

echo "Use ctrl-w and ctrl-u everywhere on macOS"
mkdir "$HOME/Library/KeyBindings" && \
  cp "$WORK_DIR/macos_DefaultKeyBinding.dict" "$HOME/Library/KeyBindings/DefaultKeyBinding.dict"

echo "NVIM c-h thinger"
infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
tic $TERM.ti

if which brew > /dev/null && [ -f "$WORK_DIR/Brewfile" ]; then
  brew bundle
else
  cat <<MSG
Homebrew is not installed.  Install then run:

  $ brew bundle

MSG
fi
