#!/usr/bin/env bash

WORKING_DIR="$HOME/dotfiles"

cd "$WORKING_DIR"

DOTFILES="alacritty.yml \
  zshrc \
  zshenv \
  zlogin \
  bashrc \
  tmux.conf \
  vim \
  vimrc \
  config/nvim/init.vim \
  gitconfig \
  cvsignore \
  psqlrc \
  irbrc \
  gemrc"

echo "Symlinking:"
mkdir -p config/nvim 2>/dev/null
for file in $DOTFILES; do
  ln -snf "$WORKING_DIR/$file" "$WORKING_DIR/.$file"
  echo "  * $file"
done

echo "Use ctrl-w and ctrl-u everywhere on macOS"
KEY_BINDINGS="$HOME/Library/KeyBindings" 
[ ! -d "$KEY_BINDINGS" ] && mkdir "$KEY_BINDINGS" && \
  cp "$WORKING_DIR/macos_DefaultKeyBinding.dict" "$KEY_BINDINGS/DefaultKeyBinding.dict"

if command -v brew > /dev/null && [ -f "$WORKING_DIR/Brewfile" ]; then
  brew bundle
else
  cat <<MSG
Homebrew is not installed.  Install then run:

  $ brew bundle

MSG
fi
